id = "meson"
name = "Meson"
version = "0.5.0"
schema_version = 1
authors = ["Job Paardekooper <job@jpsoftware.nl>"]
description = "Extension for the Meson build system."
repository = "https://github.com/jobpaardekooper/zed-meson"

[grammars.meson]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-meson"
commit = "c84f3540624b81fc44067030afce2ff78d6ede05"

[language_servers.mesonlsp]
name = "MesonLSP"
language = "Meson"

[language_servers.muon]
name = "Muon"
language = "Meson"
